name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "Hello Mohamed Mohsen"
      
      - name: second step multi_run command
        run: |
            echo "second step cli1"
            echo "second step cli2"
